version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: C0mp4ny
      MYSQL_DATABASE: shortener_url
    ports:
      - "58721:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
